from setuptools import setup, find_packages

setup(
    name="tardbot",
    version="0.1.0",
    description="TardBot: Small Language Model with MoE, Tool Calling, and CoT Reasoning",
    author="TardBot Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.1.0",
        "transformers>=4.35.0",
        "tokenizers>=0.15.0",
        "datasets>=2.14.0",
        "accelerate>=0.24.0",
        "sentencepiece>=0.1.99",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "tqdm>=4.66.0",
        "wandb>=0.15.0",
        "tensorboard>=2.14.0",
        "duckduckgo-search>=4.1.0",
        "selenium>=4.15.0",
        "playwright>=1.40.0",
        "pygments>=2.16.0",
        "psutil>=5.9.0",
        "pyyaml>=6.0.1",
        "protobuf>=4.25.0",
        "safetensors>=0.4.0",
        "packaging>=23.2",
    ],
    entry_points={
        "console_scripts": [
            "tardbot-download-corpus=scripts.download_corpus:main",
            "tardbot-train-tokenizer=scripts.train_tokenizer:main",
            "tardbot-train-experts=scripts.train_experts:main",
            "tardbot-pretrain=scripts.pretrain:main",
            "tardbot-check-preset=scripts.check_preset:main",
            "tardbot-finetune-instruct=scripts.finetune_instruct:main",
            "tardbot-finetune-tools=scripts.finetune_tools:main",
            "tardbot-finetune-reasoning=scripts.finetune_reasoning:main",
            "tardbot-inference=scripts.inference:main",
        ],
    },
)
